name: iot_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=3.7.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  fl_chart: ^0.55.2
  intl: ^0.18.1
  qr_code_scanner: ^1.0.1
  permission_handler: ^10.4.0
  qr_flutter: ^4.1.0
  clipboard: ^0.1.3
  share_plus: ^4.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/default_profile.png
    - assets/graph_button.png
    - assets/qr_code_button.png
    - assets/profile_button.png
    - assets/settings_button.png
  uses-material-design: true
